snowflake:
  target: default
  outputs:
    default:
      type: snowflake
      account: ska67070
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      warehouse: transforming
      role: transformer
      schema: "dbt_jyeo_{{ env_var('OS_VERSION') }}"
      database: development
      threads: 8

postgres:
  target: default
  outputs:
    default:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres
      schema: public
