name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: '{{ env_var("DBT_ADAPTER") }}'
models:
  my_dbt_project:
    +materialized: table

model-paths: ['{{ env_var("DBT_MODEL_PATHS", "models") }}']
