name: ubuntu-20.04
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  run-dbt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery~=1.5.0
          pip freeze
      - name: Check dbt version
        run: dbt --version
