name: ubuntu-20.04
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  run-dbt:
    runs-on: ubuntu-20.04
    env:
      OS_VERSION: ubuntu_20_04
      WORK_DIR: ${{ github.workspace }}
      BIGQUERY_TEST_SERVICE_ACCOUNT_JSON: ${{ secrets.BIGQUERY_TEST_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Check working directory
        run: echo $WORK_DIR
      - name: Copy credentials
        run: |
          printenv BIGQUERY_TEST_SERVICE_ACCOUNT_JSON > $WORK_DIR/credentials.json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery~=1.5.0
      - name: Check dependency versions
        run: pip freeze
      - name: Check dbt version
        run: dbt --version
      - name: Test connectivity
        run: dbt debug --profiles-dir $WORK_DIR/.dbt --project-dir $WORK_DIR
