name: ubuntu-20.04-postgres-core-fecde23
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  run-dbt:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      OS_VERSION: ubuntu_20_04
      WORK_DIR: ${{ github.workspace }}
      DBT_ADAPTER: postgres
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Check working directory
        run: echo $WORK_DIR
      - name: Install dependencies from dbt-core repository
        run: |
          python -m pip install --upgrade pip
          git clone https://github.com/dbt-labs/dbt-core.git
          cd dbt-core
          git checkout fecde23
          make dev
      - name: Check dependency versions
        run: pip freeze
      - name: Run dbt project
        run: dbt --debug build --profiles-dir $WORK_DIR/.dbt --project-dir $WORK_DIR --threads 8
